namespace Dumb.Emscripten.WGPUGenerator;

internal static class WgpuCodeRenderer
{
    public static string RenderEnumFile(WgpuEnum @enum, string @namespace) =>
        RenderHeader(@namespace) +
        WgpuNames.NEW_LINE + WgpuNames.NEW_LINE +
        RenderEnum(@enum) +
        WgpuNames.NEW_LINE;

    public static string RenderStructFile(WgpuStruct @struct, string @namespace) =>
        RenderHeader(@namespace) +
        WgpuNames.NEW_LINE + WgpuNames.NEW_LINE +
        RenderStruct(@struct) +
        WgpuNames.NEW_LINE;

    public static string RenderOpaquePointerFile(string pointerType, string @namespace) =>
        RenderHeader(@namespace) +
        WgpuNames.NEW_LINE + WgpuNames.NEW_LINE +
        RenderOpaquePointerStruct(pointerType) +
        WgpuNames.NEW_LINE;

    public static string RenderCallbackFile(WgpuCallback callback, string @namespace) =>
        RenderHeader(@namespace) +
        WgpuNames.NEW_LINE + WgpuNames.NEW_LINE +
        RenderCallback(callback) +
        WgpuNames.NEW_LINE;

    private static string RenderHeader(string @namespace) =>
        $$"""
        // <auto-generated />
        #nullable enable
        namespace {{@namespace}};
        """;

    private static string RenderEnum(WgpuEnum @enum) =>
        $$"""
        public enum {{@enum.Name}} : int
        {
        {{RenderEnumValues(@enum.Values)}}
        }
        """;

    private static string RenderEnumValues(IEnumerable<WgpuEnumValue> values) =>
        string.Join(WgpuNames.NEW_LINE, values.Select(static value => $"    {value.Name} = {value.Value},"));

    private static string RenderOpaquePointerStruct(string pointerType) =>
        $$"""
        public unsafe struct {{pointerType}}
        {
        }
        """;

    private static string RenderStruct(WgpuStruct @struct) =>
        $$"""
        public unsafe struct {{@struct.Name}}
        {
        {{RenderFields(@struct.Fields)}}
        }
        """;

    private static string RenderFields(IEnumerable<WgpuField> fields) =>
        string.Join(WgpuNames.NEW_LINE, fields.Select(static field => $"    public {WgpuTypeTranslator.Translate(field.Type)} {field.Name};"));

    private static string RenderCallback(WgpuCallback callback) =>
        $"public unsafe delegate {WgpuTypeTranslator.Translate(callback.ReturnType)} {callback.Name}({RenderParameters(callback.Parameters)});";

    private static string RenderParameters(IEnumerable<WgpuParameter> parameters) =>
        string.Join(", ", parameters.Select(static parameter => $"{WgpuTypeTranslator.Translate(parameter.Type)} {parameter.Name}"));

    public static string RenderCastFile(
        WgpuHeaderComparison comparison,
        string @namespace,
        ISet<string> availableSilkTypes,
        ISet<string> availableSilkEnumValues) =>
        RenderHeader(@namespace) +
        WgpuNames.NEW_LINE + WgpuNames.NEW_LINE +
        "using System.Runtime.CompilerServices;" + WgpuNames.NEW_LINE +
        "using Silk.NET.WebGPU;" + WgpuNames.NEW_LINE +
        WgpuNames.NEW_LINE +
        $$"""
        public static unsafe partial class WgpuCast
        {
        {{RenderPointerCasts(availableSilkTypes)}}
        {{RenderEnumCasts(comparison.Enums.Where(item => availableSilkTypes.Contains(WgpuNames.SilkTypeName(item.Source.Name))), availableSilkEnumValues)}}
        {{RenderStructCasts(
            comparison.Structs.Where(item => availableSilkTypes.Contains(WgpuNames.SilkTypeName(item.Source.Name))),
            BuildFieldCopyStructSet(comparison))}}
        }
        """ + WgpuNames.NEW_LINE;

    private static HashSet<string> BuildFieldCopyStructSet(WgpuHeaderComparison comparison)
    {
        var shiftedEnums = new HashSet<string>(
            comparison.Enums.Where(e => e.HasValueDifferences).Select(e => e.Source.Name),
            StringComparer.Ordinal);

        var needsCopy = new HashSet<string>(StringComparer.Ordinal);

        foreach (var s in comparison.Structs)
        {
            if (!s.IsLayoutCompatible)
                continue;
            if (s.FieldMaps.Any(map => shiftedEnums.Contains(map.Source.Type) || shiftedEnums.Contains(map.Silk.Type)))
                needsCopy.Add(s.Source.Name);
        }

        // Propagate: structs containing other structs that need field copy also need field copy
        bool changed;
        do
        {
            changed = false;
            foreach (var s in comparison.Structs)
            {
                if (!s.IsLayoutCompatible || needsCopy.Contains(s.Source.Name))
                    continue;
                if (s.FieldMaps.Any(map =>
                    needsCopy.Contains(map.Source.Type) || needsCopy.Contains(map.Silk.Type)))
                {
                    needsCopy.Add(s.Source.Name);
                    changed = true;
                }
            }
        } while (changed);

        return needsCopy;
    }

    private static string RenderPointerCasts(ISet<string> availableSilkTypes) =>
        string.Join(WgpuNames.NEW_LINE, WgpuNames.Pointers
            .Where(pointerType => availableSilkTypes.Contains(WgpuNames.SilkTypeName(pointerType)))
            .Select(RenderPointerCast));

    private static string RenderPointerCast(string pointerType) =>
        string.Join(WgpuNames.NEW_LINE, [
            $"    public static {pointerType}* Cast({WgpuNames.SilkTypeName(pointerType)}* ptr) => ({pointerType}*)ptr;",
            $"    public static {WgpuNames.SilkTypeName(pointerType)}* Cast({pointerType}* ptr) => ({WgpuNames.SilkTypeName(pointerType)}*)ptr;",
        ]);

    private static string RenderEnumCasts(IEnumerable<WgpuEnumComparison> enums, ISet<string> availableSilkEnumValues) =>
        string.Join(WgpuNames.NEW_LINE + WgpuNames.NEW_LINE, enums.Select(item => RenderEnumCast(item, availableSilkEnumValues)));

    private static string RenderEnumCast(WgpuEnumComparison comparison, ISet<string> availableSilkEnumValues)
    {
        var silkName = WgpuNames.SilkTypeName(comparison.Source.Name);
        var valueMaps = comparison.ValueMaps
            .Where(map => availableSilkEnumValues.Contains(silkName + "." + map.Silk.Name))
            .ToArray();

        if (!valueMaps.Any(static map => map.Source.Value != map.Silk.Value))
            return string.Join(WgpuNames.NEW_LINE, [
                $"    public static {comparison.Source.Name} Cast(this {silkName} v) => ({comparison.Source.Name})v;",
                $"    public static {silkName} Cast(this {comparison.Source.Name} v) => ({silkName})v;",
            ]);

        return string.Join(WgpuNames.NEW_LINE + WgpuNames.NEW_LINE, [
            RenderEnumValueMap(comparison.Source.Name, silkName, valueMaps, silkToSource: true),
            RenderEnumValueMap(comparison.Source.Name, silkName, valueMaps, silkToSource: false),
        ]);
    }

    private static string RenderEnumValueMap(string sourceName, string silkName, WgpuEnumValueMap[] maps, bool silkToSource)
    {
        var sourceType = silkToSource ? silkName : sourceName;
        var targetType = silkToSource ? sourceName : silkName;
        var cases = maps
            .Where(static map => map.Source.Value != map.Silk.Value)
            .Select(map => silkToSource
                ? $"        {silkName}.{map.Silk.Name} => {sourceName}.{map.Source.Name},"
                : $"        {sourceName}.{map.Source.Name} => {silkName}.{map.Silk.Name},");

        return string.Join(WgpuNames.NEW_LINE, [
            $"    public static {targetType} Cast(this {sourceType} v) => v switch",
            "    {",
            ..cases,
            $"        _ => ({targetType})v,",
            "    };",
        ]);
    }

    private static string RenderStructCasts(
        IEnumerable<WgpuStructComparison> structs,
        ISet<string> fieldCopyStructNames) =>
        string.Join(WgpuNames.NEW_LINE, structs.Select(s => RenderStructCast(s, fieldCopyStructNames)));

    private static string RenderStructCast(WgpuStructComparison comparison, ISet<string> fieldCopyStructNames)
    {
        var silkName = WgpuNames.SilkTypeName(comparison.Source.Name);

        if (!comparison.IsLayoutCompatible)
            return RenderUncastableStructComment(comparison, silkName);

        return fieldCopyStructNames.Contains(comparison.Source.Name)
            ? RenderFieldCopyCast(comparison, silkName)
            : string.Join(WgpuNames.NEW_LINE, [
                $"    public static ref {comparison.Source.Name} Cast(this ref {silkName} v) => ref Unsafe.As<{silkName}, {comparison.Source.Name}>(ref v);",
                $"    public static ref {silkName} Cast(this ref {comparison.Source.Name} v) => ref Unsafe.As<{comparison.Source.Name}, {silkName}>(ref v);",
            ]);
    }

    private static string RenderFieldCopyCast(WgpuStructComparison comparison, string silkName)
    {
        var sourceName = comparison.Source.Name;
        return string.Join(WgpuNames.NEW_LINE + WgpuNames.NEW_LINE, [
            RenderOneFieldCopy(comparison, inputType: silkName, outputType: sourceName),
            RenderOneFieldCopy(comparison, inputType: sourceName, outputType: silkName),
        ]);
    }

    private static string RenderOneFieldCopy(
        WgpuStructComparison comparison, string inputType, string outputType)
    {
        var silkToSource = inputType != comparison.Source.Name;
        var assignments = comparison.FieldMaps
            .Select(map => RenderFieldAssignment(map, silkToSource))
            .ToArray();

        return string.Join(WgpuNames.NEW_LINE, [
            $"    public static {outputType} Cast(this {inputType} v)",
            "    {",
            $"        Unsafe.SkipInit(out {outputType} result);",
            ..assignments,
            "        return result;",
            "    }",
        ]);
    }

    private static string RenderFieldAssignment(WgpuFieldMap map, bool silkToSource)
    {
        var srcField = silkToSource ? map.Silk : map.Source;
        var tgtField = silkToSource ? map.Source : map.Silk;
        var tgtCsType = silkToSource
            ? WgpuTypeTranslator.Translate(tgtField.Type)
            : WgpuTypeTranslator.TranslateSilk(tgtField.Type);
        var srcCsType = silkToSource
            ? WgpuTypeTranslator.TranslateSilk(srcField.Type)
            : WgpuTypeTranslator.Translate(srcField.Type);

        string rhs;
        if (srcCsType == tgtCsType)
            rhs = $"v.{srcField.Name}";
        else if (tgtCsType.EndsWith("*", StringComparison.Ordinal) && srcCsType.EndsWith("*", StringComparison.Ordinal))
            rhs = $"({tgtCsType})v.{srcField.Name}";
        else
            rhs = $"v.{srcField.Name}.Cast()";

        return $"        result.{tgtField.Name} = {rhs};";
    }

    private static string RenderUncastableStructComment(WgpuStructComparison comparison, string silkName)
    {
        var reasons = new List<string>();

        var mappedSourceNames = new HashSet<string>(comparison.FieldMaps.Select(static m => m.Source.Name), StringComparer.Ordinal);
        var silkFieldDict = comparison.Silk.Fields.ToDictionary(static f => f.Name, StringComparer.Ordinal);

        foreach (var sourceField in comparison.Source.Fields)
        {
            if (!mappedSourceNames.Contains(sourceField.Name))
            {
                reasons.Add(silkFieldDict.ContainsKey(sourceField.Name)
                    ? $"{sourceField.Name}: type diff"
                    : $"~{sourceField.Name}");
            }
            else
            {
                var map = comparison.FieldMaps.First(m => string.Equals(m.Source.Name, sourceField.Name, StringComparison.Ordinal));
                if (map.Source.Type != map.Silk.Type)
                    reasons.Add($"{sourceField.Name}: type diff");
            }
        }

        var mappedSilkNames = new HashSet<string>(comparison.FieldMaps.Select(static m => m.Silk.Name), StringComparer.Ordinal);
        foreach (var silkField in comparison.Silk.Fields)
        {
            if (!mappedSilkNames.Contains(silkField.Name))
                reasons.Add($"+{silkField.Name}");
        }

        var detail = reasons.Count > 0 ? $" ({string.Join(", ", reasons)})" : "";
        return $"    // {comparison.Source.Name} ↔ {silkName}: layout incompatible{detail}";
    }
}
